export const CHANGE_USER_ID = "CHANGE_USER_ID";
export const CHANGE_USER_NAME = "CHANGE_USER_NAME";
export const CHANGE_USER_SURNAME = "CHANGE_USER_SURNAME";
export const CHANGE_QUIZ_ID = "CHANGE_QUIZ_ID";
export const CHANGE_SCORE = "CHANGE_SCORE";
